# Override for full image mode (single channel)
OUTPUT:
  RUN_NAME: ""

INPUT:
  MODE: "full"
  CHANNELS: 1
  IMG_SIZE: 256

MODEL:
  BACKBONE: "efficientnet_b3"

AUG:
  LEVEL: "light"   # First time running, recommended "light"

TEST:
  CKPT_PATH: "${MODEL_PATH}/runs/best.ckpt"
