# Override for mask-guided mode (concat 2 channels)
OUTPUT:
  RUN_NAME: ""

INPUT:
  MODE: "mask_concat"
  CHANNELS: 2
  IMG_SIZE: 256

MODEL:
  BACKBONE: "resnet18"

AUG:
  LEVEL: "light"

TEST:
  CKPT_PATH: "${MODEL_PATH}/best.ckpt"
